### PR TITLE
Fix ambiguous expressions and spelling variations

### PR DESCRIPTION
**Pull request by nowsprinting**
### Changes

- "project" to "game title"
    - Exclude: Unity project
- "title" to "game title"
    - Exclude: Title scene
- "game title own" to "game title specific" and some to "custom"

---

### Contribution License Agreement

- [x] By placing an "x" in the box, I hereby understand, accept and agree to be bound by the terms and conditions of the [Contribution License Agreement](https://dena.github.io/cla/).

### CODE REVIEW

**Review by bo40 — APPROVED** [review]
LGTM

**Comment by bo40** [comment]
@nowsprinting 
This PR has a conflict. Could you please resolve it?

**Comment by nowsprinting** [comment]
@bo40 san, Rebased! Thank you.

**Review by bo40 — APPROVED** [review]

**Comment by bo40** [comment]
Thank you!

**Pull request merged**
