### PR TITLE
Support message template and color settings for SlackReporter

### PR DESCRIPTION
**Pull request by nowsprinting**
### Changes

- Add lead text and message body template settings; can use placeholders
- Add attachments color settings

### Priority

I hope to your review && merge around one week.
There is no need to release it yet.

---

### Contribution License Agreement

- [x] By placing an "x" in the box, I hereby understand, accept and agree to be bound by the terms and conditions of the [Contribution License Agreement](https://dena.github.io/cla/).

### CODE REVIEW

**Review by bo40 — DISMISSED** [review]
LGTM

**Review by get-me-power — APPROVED** [review]
LGTM

**Comment by get-me-power** [comment]
@nowsprinting
Editor/UI/Settings/AutopilotSettingsEditor.cs
Would you resolve it?

**Comment by nowsprinting** [comment]
@get-me-power san, rebased!

**Review by get-me-power — APPROVED** [review]
LGTM

**Comment by get-me-power** [comment]
@nowsprinting 

Thanks!

**Pull request merged**
