### PR TITLE
Fix obsolete fields convert spec

### PR DESCRIPTION
**Pull request by nowsprinting**
### Changes

- Fix Loggers and Reporters convert, set to field directly to avoid complicating the state
- Fix SlackReporter convert condition and create the file. Same as a JUnitXmlReporter; see #98

### Priority

I hope to your review && merge ASAP.
There is no need to release it yet.

---

### Contribution License Agreement

- [x] By placing an "x" in the box, I hereby understand, accept and agree to be bound by the terms and conditions of the [Contribution License Agreement](https://dena.github.io/cla/).

### CODE REVIEW

**Review by asurato — DISMISSED** [review]
LGTM

**Comment by asurato** [comment]
@nowsprinting 
Runtime/Settings/AutopilotSettings.cs is conflicting.
Would you merge it?

**Comment by nowsprinting** [comment]
@asurato san, Thanks! please waiting!

**Comment by nowsprinting** [comment]
@asurato san, rebased!

I will rebase other PRs tonight after merging this PR.

**Review by asurato — APPROVED** [review]

**Comment by asurato** [comment]
Thank you for your contribution!

**Pull request merged**
