### PR TITLE
Fix test asset name

### PR DESCRIPTION
**Pull request by nowsprinting**
### Changes
- Test asset name (not displayed in inspector window)

### Reason
- Forgot to change

---

### Contribution License Agreement

- [x] By placing an "x" in the box, I hereby understand, accept and agree to be bound by the terms and conditions of the [Contribution License Agreement](https://dena.github.io/cla/).

### CODE REVIEW

**Comment by nowsprinting** [comment]
The label should be `bug`, but it set `fix` ???

**Comment by nowsprinting** [comment]
ok, need the forked owner's name in the setting file.

**Comment by Kesin11** [comment]
If you turn on [debug mode](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) and re-run it, you may find the cause.

**Comment by nowsprinting** [comment]
I can not re-run, it because I'm not owner!

**Comment by nowsprinting** [comment]
maybe, https://github.com/TimonVS/pr-labeler-action/blob/9de3270d8cac2f0be966127f6740b04fe001f9ff/src/utils/config.ts#L31-L35

**Comment by Kesin11** [comment]
I just re-ran with debug option, but I couldn't get anything new about pr-labeler-action behavior. 😭

**Comment by nowsprinting** [comment]
Plz wait for merge this PR:
https://github.com/TimonVS/pr-labeler-action/pull/80

**Review by Kuniwak — APPROVED** [review]
Looks Good To Me. Sorry for my tooooooo late reply.

**Pull request merged**
