### PR TITLE
Multiple Loggers and Reporters support

### PR DESCRIPTION
**Pull request by nowsprinting**
### Before

- Single Logger instance can be set to AutopilotSettings.loggerAsset field.
- Single Reporter instance can be set to AutopilotSettings.reporter field.

### After

- Multiple Logger instances can be set to AutopilotSettings.loggerAssets field.
- Multiple Reporter instances can be set to AutopilotSettings.reporters field.

### Other Changes

- Single Logger/ Reporter setting field is obsolete.
- Converting legacy Logger/ Reporter settings to new multiple Loggers/ Reporters
- Refactor initialize settings
- Remove CompositeLogger/ Reporter from the context menu
- Mod SlackReporter order in the context menu
- Fix disabling Reset button

### Priority

I hope to review && merge in this week.
There is no need to release it yet.

---

### Contribution License Agreement

- [x] By placing an "x" in the box, I hereby understand, accept and agree to be bound by the terms and conditions of the [Contribution License Agreement](https://dena.github.io/cla/).

### CODE REVIEW

**Review by asurato — APPROVED** [review]
LGTM

**Comment by asurato** [comment]
@nowsprinting
Will you resolve conflicts?

**Comment by nowsprinting** [comment]
@asurato san, ok, please wait.

**Comment by nowsprinting** [comment]
@asurato san, I completed rebase && tests!
Please merge it. Thank you!

**Review by asurato — APPROVED** [review]

**Pull request merged**
